/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classes;

import java.awt.Font;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.FontUIResource;

public class Start extends javax.swing.JFrame {
   private PreparedStatement pst = null;
    private  ResultSet rs = null;
    private final java.sql.Connection conn;
   
    
    public Start() {
        initComponents();
        conn = Connection.connexion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnConnect = new javax.swing.JButton();
        desc = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        password = new javax.swing.JPasswordField();
        email = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(350, 200, 0, 0));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnConnect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BtnConnect.png"))); // NOI18N
        btnConnect.setBorder(null);
        btnConnect.setBorderPainted(false);
        btnConnect.setContentAreaFilled(false);
        btnConnect.setDefaultCapable(false);
        btnConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectActionPerformed(evt);
            }
        });
        jPanel1.add(btnConnect, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, -1, -1));

        desc.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        desc.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(desc, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 290, 30));

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setFont(new java.awt.Font("Cantarell", 2, 12)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox1.setText("Make the password visible?");
        jCheckBox1.setBorder(null);
        jCheckBox1.setFocusable(false);
        jCheckBox1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PasswordVisibility.png"))); // NOI18N
        jCheckBox1.setOpaque(false);
        jCheckBox1.setRequestFocusEnabled(false);
        jCheckBox1.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, -1, -1));

        password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                passwordMouseReleased(evt);
            }
        });
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 258, 280, 40));

        email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                emailMouseReleased(evt);
            }
        });
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 280, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/NewLogin.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailMouseReleased
         desc.setText("Enter the email");
    }//GEN-LAST:event_emailMouseReleased

    private void passwordMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMouseReleased
         desc.setText("Enter the password");
    }//GEN-LAST:event_passwordMouseReleased

    private void btnConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectActionPerformed
            
          String query = "select * from lms_users  where email =? and password =?";
        try {
            pst = conn.prepareStatement(query);
            pst.setString(1, email.getText());
            pst.setString(2, String.valueOf(password.getPassword()));
            rs = pst.executeQuery();
            if(rs.next()){
             dispose();
             Dashboard welcome = new Dashboard();
             welcome.setVisible(true);
            }
            else{
             desc.setText("Email or password incorrect");
            }
         
        } catch (SQLException e) {
            System.out.println("---------> SQL exception :"+e);
        }
    }//GEN-LAST:event_btnConnectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
   UIManager.put("OptionPane.messageFont", new FontUIResource(new Font("Trebuchet MS",Font.PLAIN,18)));
        try {
              UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
            
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException ignored) {
            // TODO: handle exception
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Start().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConnect;
    private javax.swing.JLabel desc;
    private javax.swing.JTextField email;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField password;
    // End of variables declaration//GEN-END:variables
}
